export const reviews = [
  {
    'name': 'Alice',
    'comment': '¡Excelente producto! Me encanta.',
    'date': '12-05-2023',
    'rating': 3,
    'category': 'smartphones',
  },
  {
    'name': 'Bob',
    'comment': 'Muy útil, lo recomiendo.',
    'date': '15-09-2023',
    'rating': 4,
    'category': 'smartphones',
  },
  {
    'name': 'Charlie',
    'comment': 'Calidad excepcional.',
    'date': '21-07-2023',
    'rating': 5,
    'category': 'smartphones',
  },
  {
    'name': 'Diana',
    'comment': 'Buen precio por lo que ofrece.',
    'date': '03-06-2023',
    'rating': 4,
    'category': 'laptops',
  },
  {
    'name': 'Eva',
    'comment': 'Cumple con lo esperado.',
    'date': '17-08-2023',
    'rating': 4,
    'category': 'laptops',
  },
  {
    'name': 'Frank',
    'comment': 'Fácil de usar y práctico.',
    'date': '30-10-2023',
    'rating': 3,
    'category': 'laptops',
  },
  {
    'name': 'Gina',
    'comment': 'Me sorprendió gratamente.',
    'date': '08-09-2023',
    'rating': 4,
    'category': 'fragrances',
  },
  {
    'name': 'Henry',
    'comment': 'Lo volvería a comprar sin dudarlo.',
    'date': '06-07-2023',
    'rating': 5,
    'category': 'fragrances',
  },
  {
    'name': 'Ivy',
    'comment': 'Satisfecho con la compra.',
    'date': '24-05-2023',
    'rating': 4,
    'category': 'fragrances',
  },
  {
    'name': 'Jack',
    'comment': 'Perfecto para mis necesidades.',
    'date': '02-11-2023',
    'rating': 4,
    'category': 'skincare',
  },
  {
    'name': 'Kate',
    'comment': 'Deja la piel suave y fresca.',
    'date': '11-08-2023',
    'rating': 5,
    'category': 'skincare',
  },
  {
    'name': 'Liam',
    'comment': 'Resultados visibles en poco tiempo.',
    'date': '28-06-2023',
    'rating': 4,
    'category': 'skincare',
  },
  {
    'name': 'Mia',
    'comment': 'Buena relación calidad-precio.',
    'date': '25-09-2023',
    'rating': 4,
    'category': 'groceries',
  },
  {
    'name': 'Noah',
    'comment': 'Productos frescos y de buena calidad.',
    'date': '05-05-2023',
    'rating': 3,
    'category': 'groceries',
  },
  {
    'name': 'Olivia',
    'comment': 'Amplia variedad de productos.',
    'date': '14-07-2023',
    'rating': 2,
    'category': 'groceries',
  },
  {
    'name': 'Sophia',
    'comment': 'Hermosos diseños y buena calidad.',
    'date': '20-08-2023',
    'rating': 2,
    'category': 'home-decoration',
  },
  {
    'name': 'William',
    'comment': 'Bien.',
    'date': '18-10-2023',
    'rating': 1,
    'category': 'home-decoration',
  },
  {
    'name': 'Victoria',
    'comment': 'Muebles elegantes y cómodos.',
    'date': '10-09-2023',
    'rating': 4,
    'category': 'home-decoration',
  },
  {
    'name': 'Xavier',
    'comment': 'Camisas de buena calidad.',
    'date': '07-11-2023',
    'rating': 3,
    'category': 'mens-shirts',
  },
  {
    'name': 'Yara',
    'comment': 'Muy cómodos y frescos.',
    'date': '16-06-2023',
    'rating': 4,
    'category': 'mens-shirts',
  },
  {
    'name': 'Zoe',
    'comment': 'Zapatos resistentes y modernos.',
    'date': '29-07-2023',
    'rating': 3,
    'category': 'mens-shoes',
  },
  {
    'name': 'Aaron',
    'comment': 'Excelente calidad y diseño.',
    'date': '04-08-2023',
    'rating': 3,
    'category': 'mens-shoes',
  },
  {
    'name': 'Bella',
    'comment': 'Elegancia y estilo en cada detalle.',
    'date': '19-05-2023',
    'rating': 3,
    'category': 'womens-dresses',
  },
  {
    'name': 'Christian',
    'comment': 'Buena relación calidad-precio.',
    'date': '22-09-2023',
    'rating': 4,
    'category': 'womens-dresses',
  },
  {
    'name': 'Dylan',
    'comment': 'Zapatos cómodos y elegantes.',
    'date': '12-10-2023',
    'rating': 3,
    'category': 'womens-shoes',
  },
  {
    'name': 'Emily',
    'comment': 'Me encantan, son perfectos.',
    'date': '30-07-2023',
    'rating': 4,
    'category': 'womens-shoes',
  },
  {
    'name': 'Fiona',
    'comment': 'Relojes de gran calidad.',
    'date': '09-06-2023',
    'rating': 4,
    'category': 'mens-watches',
  },
  {
    'name': 'Gabriel',
    'comment': 'Elegancia y precisión.',
    'date': '27-05-2023',
    'rating': 2,
    'category': 'mens-watches',
  },
  {
    'name': 'Hannah',
    'comment': 'Diseños femeninos y encantadores.',
    'date': '14-11-2023',
    'rating': 3,
    'category': 'womens-watches',
  },
]
