export const reviews = [
  {
    'name': 'Alice',
    'comment': '¡Excelente producto! Me encanta.',
    'date': '2023-05-12',
    'rating': 5,
    'category': 'smartphones',
  },
  {
    'name': 'Bob',
    'comment': 'Muy útil, lo recomiendo.',
    'date': '2023-09-15',
    'rating': 4,
    'category': 'smartphones',
  },
  {
    'name': 'Charlie',
    'comment': 'Calidad excepcional.',
    'date': '2023-07-21',
    'rating': 5,
    'category': 'smartphones',
  },
  {
    'name': 'Diana',
    'comment': 'Buen precio por lo que ofrece.',
    'date': '2023-06-03',
    'rating': 4,
    'category': 'laptops',
  },
  {
    'name': 'Eva',
    'comment': 'Cumple con lo esperado.',
    'date': '2023-08-17',
    'rating': 4,
    'category': 'laptops',
  },
  {
    'name': 'Frank',
    'comment': 'Fácil de usar y práctico.',
    'date': '2023-10-30',
    'rating': 5,
    'category': 'laptops',
  },
  {
    'name': 'Gina',
    'comment': 'Me sorprendió gratamente.',
    'date': '2023-09-08',
    'rating': 5,
    'category': 'fragrances',
  },
  {
    'name': 'Henry',
    'comment': 'Lo volvería a comprar sin dudarlo.',
    'date': '2023-07-06',
    'rating': 5,
    'category': 'fragrances',
  },
  {
    'name': 'Ivy',
    'comment': 'Satisfecho con la compra.',
    'date': '2023-05-24',
    'rating': 4,
    'category': 'fragrances',
  },
  {
    'name': 'Jack',
    'comment': 'Perfecto para mis necesidades.',
    'date': '2023-11-02',
    'rating': 4,
    'category': 'skincare',
  },
  {
    'name': 'Kate',
    'comment': 'Deja la piel suave y fresca.',
    'date': '2023-08-11',
    'rating': 5,
    'category': 'skincare',
  },
  {
    'name': 'Liam',
    'comment': 'Resultados visibles en poco tiempo.',
    'date': '2023-06-28',
    'rating': 4,
    'category': 'skincare',
  },
  {
    'name': 'Mia',
    'comment': 'Buena relación calidad-precio.',
    'date': '2023-09-25',
    'rating': 4,
    'category': 'groceries',
  },
  {
    'name': 'Noah',
    'comment': 'Productos frescos y de buena calidad.',
    'date': '2023-05-05',
    'rating': 5,
    'category': 'groceries',
  },
  {
    'name': 'Olivia',
    'comment': 'Amplia variedad de productos.',
    'date': '2023-07-14',
    'rating': 4,
    'category': 'groceries',
  },
  {
    'name': 'Sophia',
    'comment': 'Hermosos diseños y buena calidad.',
    'date': '2023-08-20',
    'rating': 5,
    'category': 'home-decoration',
  },
  {
    'name': 'William',
    'comment': 'Aporta un toque especial a mi hogar.',
    'date': '2023-10-18',
    'rating': 5,
    'category': 'home-decoration',
  },
  {
    'name': 'Victoria',
    'comment': 'Muebles elegantes y cómodos.',
    'date': '2023-09-10',
    'rating': 4,
    'category': 'home-decoration',
  },
  {
    'name': 'Xavier',
    'comment': 'Camisas de buena calidad.',
    'date': '2023-11-07',
    'rating': 4,
    'category': 'mens-shirts',
  },
  {
    'name': 'Yara',
    'comment': 'Muy cómodos y frescos.',
    'date': '2023-06-16',
    'rating': 5,
    'category': 'mens-shirts',
  },
  {
    'name': 'Zoe',
    'comment': 'Zapatos resistentes y modernos.',
    'date': '2023-07-29',
    'rating': 5,
    'category': 'mens-shoes',
  },
  {
    'name': 'Aaron',
    'comment': 'Excelente calidad y diseño.',
    'date': '2023-08-04',
    'rating': 5,
    'category': 'mens-shoes',
  },
  {
    'name': 'Bella',
    'comment': 'Elegancia y estilo en cada detalle.',
    'date': '2023-05-19',
    'rating': 5,
    'category': 'womens-dresses',
  },
  {
    'name': 'Christian',
    'comment': 'Buena relación calidad-precio.',
    'date': '2023-09-22',
    'rating': 4,
    'category': 'womens-dresses',
  },
  {
    'name': 'Dylan',
    'comment': 'Zapatos cómodos y elegantes.',
    'date': '2023-10-12',
    'rating': 5,
    'category': 'womens-shoes',
  },
  {
    'name': 'Emily',
    'comment': 'Me encantan, son perfectos.',
    'date': '2023-07-30',
    'rating': 5,
    'category': 'womens-shoes',
  },
  {
    'name': 'Fiona',
    'comment': 'Relojes de gran calidad.',
    'date': '2023-06-09',
    'rating': 4,
    'category': 'mens-watches',
  },
  {
    'name': 'Gabriel',
    'comment': 'Elegancia y precisión.',
    'date': '2023-05-27',
    'rating': 5,
    'category': 'mens-watches',
  },
  {
    'name': 'Hannah',
    'comment': 'Diseños femeninos y encantadores.',
    'date': '2023-11-14',
    'rating': 5,
    'category': 'womens-watches',
  },
]
